// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * AIAgentConfigPublic
 */
export type AiAgentConfigPublic = {
    /**
     * Provider
     */
    provider?: string;
    /**
     * Model
     */
    model?: string;
    /**
     * Cover Image Model
     */
    cover_image_model?: string;
    /**
     * Temperature
     */
    temperature?: number;
    /**
     * System Prompt
     */
    system_prompt?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Saved Api Keys
     */
    saved_api_keys?: {
        [key: string]: boolean;
    };
    /**
     * Ollama Base Url
     */
    ollama_base_url?: string | null;
};

/**
 * AIAgentConfigUpdate
 */
export type AiAgentConfigUpdate = {
    /**
     * Provider
     */
    provider?: string | null;
    /**
     * Model
     */
    model?: string | null;
    /**
     * Cover Image Model
     */
    cover_image_model?: string | null;
    /**
     * Temperature
     */
    temperature?: number | null;
    /**
     * System Prompt
     */
    system_prompt?: string | null;
    /**
     * Ollama Base Url
     */
    ollama_base_url?: string | null;
    /**
     * Provider Api Keys
     */
    provider_api_keys?: {
        [key: string]: string;
    } | null;
    /**
     * Openai Api Key
     */
    openai_api_key?: string | null;
    /**
     * Anthropic Api Key
     */
    anthropic_api_key?: string | null;
    /**
     * Gemini Api Key
     */
    gemini_api_key?: string | null;
    /**
     * Groq Api Key
     */
    groq_api_key?: string | null;
    /**
     * Openrouter Api Key
     */
    openrouter_api_key?: string | null;
};

/**
 * AIModelOption
 */
export type AiModelOption = {
    /**
     * Id
     */
    id: string;
    /**
     * Label
     */
    label: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Context Window Tokens
     */
    context_window_tokens?: number | null;
};

/**
 * AIModelsCatalogPublic
 */
export type AiModelsCatalogPublic = {
    /**
     * Providers
     */
    providers: Array<AiProviderCatalogPublic>;
    /**
     * Cover Image Models
     */
    cover_image_models: Array<CoverImageModelOption>;
    /**
     * Default Cover Image Model
     */
    default_cover_image_model: string;
    /**
     * Credential Providers
     */
    credential_providers: Array<AiProviderCredentialPublic>;
    ollama?: OllamaCatalogStatus | null;
};

/**
 * AIProviderCatalogPublic
 */
export type AiProviderCatalogPublic = {
    /**
     * Slug
     */
    slug: string;
    /**
     * Label
     */
    label: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Default Model
     */
    default_model: string;
    /**
     * Models
     */
    models: Array<AiModelOption>;
    /**
     * Requires Api Key
     */
    requires_api_key?: boolean;
    /**
     * Auth Style
     */
    auth_style?: string;
    /**
     * Sort Order
     */
    sort_order?: number;
    /**
     * Models Source
     *
     * catalog = database seed; ollama/live = fetched from provider API
     */
    models_source?: string;
    /**
     * Provider Id
     *
     * Set for user-created custom providers
     */
    provider_id?: string | null;
    /**
     * Is Custom
     */
    is_custom?: boolean;
    /**
     * Can Refresh Models
     */
    can_refresh_models?: boolean;
};

/**
 * AIProviderCredentialPublic
 */
export type AiProviderCredentialPublic = {
    /**
     * Slug
     */
    slug: string;
    /**
     * Label
     */
    label: string;
    /**
     * Requires Api Key
     */
    requires_api_key?: boolean;
    /**
     * Auth Style
     */
    auth_style?: string;
};

/**
 * Body_login_access_token_api_v1_login_access_token_post
 */
export type BodyLoginAccessTokenApiV1LoginAccessTokenPost = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * Body_upload_content_draft_cover_image_api_v1_content_drafts__draft_id__covers__cover_id__image_post
 */
export type BodyUploadContentDraftCoverImageApiV1ContentDraftsDraftIdCoversCoverIdImagePost = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * ContentDraftDetailPublic
 */
export type ContentDraftDetailPublic = {
    /**
     * Topic
     */
    topic: string;
    /**
     * User Prompt
     */
    user_prompt?: string | null;
    status?: ContentDraftStatus;
    /**
     * Id
     */
    id: string;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    devto_article?: DevtoArticlePublic | null;
    linkedin_post?: LinkedinPostPublic | null;
    /**
     * Cover Images
     */
    cover_images?: Array<CoverImagePublic>;
    /**
     * Cover Image Warning
     *
     * Set when cover image generation was skipped or failed
     */
    cover_image_warning?: string | null;
    publish_job?: PublishJobPublic | null;
    /**
     * Linkedin Clipboard Text
     *
     * LinkedIn teaser with live DEV.to URL when available
     */
    linkedin_clipboard_text?: string | null;
};

/**
 * ContentDraftPublic
 */
export type ContentDraftPublic = {
    /**
     * Topic
     */
    topic: string;
    /**
     * User Prompt
     */
    user_prompt?: string | null;
    status?: ContentDraftStatus;
    /**
     * Id
     */
    id: string;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * ContentDraftStatus
 */
export type ContentDraftStatus = 'draft' | 'approved' | 'scheduled' | 'published' | 'partially_published' | 'failed';

/**
 * ContentDraftsPublic
 */
export type ContentDraftsPublic = {
    /**
     * Data
     */
    data: Array<ContentDraftPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * CoverImageModelOption
 */
export type CoverImageModelOption = {
    /**
     * Id
     */
    id: string;
    /**
     * Label
     */
    label: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Context Window Tokens
     */
    context_window_tokens?: number | null;
    /**
     * Key Provider
     *
     * Provider slug whose API key is required for this cover model
     */
    key_provider: string;
};

/**
 * CoverImagePlatform
 */
export type CoverImagePlatform = 'devto' | 'linkedin';

/**
 * CoverImagePublic
 */
export type CoverImagePublic = {
    /**
     * Id
     */
    id: string;
    platform: CoverImagePlatform;
    /**
     * Storage Key
     */
    storage_key: string | null;
    /**
     * Prompt Used
     */
    prompt_used: string | null;
    /**
     * Provider
     */
    provider: string | null;
    /**
     * Image Url
     */
    image_url?: string | null;
};

/**
 * CustomAIProviderCreate
 */
export type CustomAiProviderCreate = {
    /**
     * Display Name
     */
    display_name: string;
    /**
     * Base Url
     */
    base_url: string;
    /**
     * Api Adapter
     *
     * openai_compatible or ollama
     */
    api_adapter?: string;
    /**
     * Auth Style
     */
    auth_style?: string;
    /**
     * Auth Header Name
     */
    auth_header_name?: string | null;
    /**
     * Api Key
     */
    api_key?: string | null;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * CustomAIProviderPublic
 */
export type CustomAiProviderPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Slug
     */
    slug: string;
    /**
     * Display Name
     */
    display_name: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Base Url
     */
    base_url: string;
    /**
     * Api Adapter
     */
    api_adapter: string;
    /**
     * Auth Style
     */
    auth_style: string;
    /**
     * Requires Api Key
     */
    requires_api_key: boolean;
    /**
     * Has Api Key
     */
    has_api_key: boolean;
    /**
     * Models Source
     */
    models_source?: string;
};

/**
 * DevtoArticlePublic
 */
export type DevtoArticlePublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Title
     */
    title: string;
    /**
     * Body Markdown
     */
    body_markdown: string;
    /**
     * Tags
     */
    tags: string;
    /**
     * Cover Image Id
     */
    cover_image_id: string | null;
};

/**
 * ErrorDetail
 */
export type ErrorDetail = {
    /**
     * Detail
     *
     * A specific error message suitable for UI display
     */
    detail: string;
};

/**
 * GenerateDraftRequest
 */
export type GenerateDraftRequest = {
    /**
     * Topic
     */
    topic: string;
    /**
     * User Prompt
     */
    user_prompt?: string | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * LinkedinPostPublic
 */
export type LinkedinPostPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Teaser Text
     */
    teaser_text: string;
    /**
     * Article Url
     */
    article_url: string | null;
    /**
     * Cover Image Id
     */
    cover_image_id: string | null;
};

/**
 * Message
 */
export type Message = {
    /**
     * Message
     *
     * A human-readable success or status message
     */
    message: string;
};

/**
 * OllamaCatalogStatus
 */
export type OllamaCatalogStatus = {
    /**
     * Base Url
     */
    base_url: string;
    /**
     * Reachable
     */
    reachable: boolean;
    /**
     * Message
     */
    message?: string | null;
    /**
     * Model Count
     */
    model_count?: number;
};

/**
 * Page[UserActivityPublic]
 */
export type PageUserActivityPublic = {
    /**
     * Items
     */
    items: Array<UserActivityPublic>;
    /**
     * Total
     */
    total: number;
    /**
     * Page
     */
    page: number;
    /**
     * Size
     */
    size: number;
    /**
     * Pages
     */
    pages: number;
};

/**
 * Page[UserPublic]
 */
export type PageUserPublic = {
    /**
     * Items
     */
    items: Array<UserPublic>;
    /**
     * Total
     */
    total: number;
    /**
     * Page
     */
    page: number;
    /**
     * Size
     */
    size: number;
    /**
     * Pages
     */
    pages: number;
};

/**
 * PasswordHistoriesPublic
 */
export type PasswordHistoriesPublic = {
    /**
     * Data
     */
    data: Array<PasswordHistoryPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * PasswordHistoryPublic
 */
export type PasswordHistoryPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * PlatformConfigPublic
 */
export type PlatformConfigPublic = {
    /**
     * Devto Enabled
     */
    devto_enabled?: boolean;
    /**
     * Linkedin Enabled
     */
    linkedin_enabled?: boolean;
    /**
     * Devto Profile Url
     */
    devto_profile_url?: string | null;
    /**
     * Linkedin Profile Url
     */
    linkedin_profile_url?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Has Devto Api Key
     */
    has_devto_api_key?: boolean;
};

/**
 * PlatformConfigUpdate
 */
export type PlatformConfigUpdate = {
    /**
     * Devto Enabled
     */
    devto_enabled?: boolean | null;
    /**
     * Linkedin Enabled
     */
    linkedin_enabled?: boolean | null;
    /**
     * Devto Profile Url
     */
    devto_profile_url?: string | null;
    /**
     * Linkedin Profile Url
     */
    linkedin_profile_url?: string | null;
    /**
     * Devto Api Key
     */
    devto_api_key?: string | null;
};

/**
 * ProviderModelsRefreshPublic
 */
export type ProviderModelsRefreshPublic = {
    /**
     * Slug
     */
    slug: string;
    /**
     * Models
     */
    models: Array<AiModelOption>;
    /**
     * Added Count
     */
    added_count?: number;
    /**
     * Total Count
     */
    total_count?: number;
    /**
     * Message
     */
    message?: string | null;
};

/**
 * PublishJobPublic
 */
export type PublishJobPublic = {
    /**
     * Id
     */
    id: string;
    status: PublishJobStatus;
    /**
     * Retry Count
     */
    retry_count: number;
    /**
     * Devto Url
     */
    devto_url: string | null;
    /**
     * Error Message
     */
    error_message: string | null;
    /**
     * Scheduled At
     */
    scheduled_at: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * PublishJobStatus
 */
export type PublishJobStatus = 'pending' | 'running' | 'completed' | 'failed' | 'partial';

/**
 * PublishStatusPublic
 */
export type PublishStatusPublic = {
    draft_status: ContentDraftStatus;
    publish_job?: PublishJobPublic | null;
    /**
     * Linkedin Clipboard Text
     */
    linkedin_clipboard_text?: string | null;
};

/**
 * RescheduleDraftRequest
 */
export type RescheduleDraftRequest = {
    /**
     * Scheduled At
     *
     * New publish time (UTC) for a scheduled draft.
     */
    scheduled_at: string;
};

/**
 * ScheduleDraftRequest
 */
export type ScheduleDraftRequest = {
    /**
     * Scheduled At
     *
     * When to publish (UTC). Omit for immediate publish on first schedule.
     */
    scheduled_at?: string | null;
};

/**
 * Token
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
};

/**
 * UpdateDraftRequest
 */
export type UpdateDraftRequest = {
    /**
     * Devto Title
     */
    devto_title?: string | null;
    /**
     * Devto Body Markdown
     */
    devto_body_markdown?: string | null;
    /**
     * Devto Tags
     */
    devto_tags?: string | null;
    /**
     * Linkedin Teaser
     */
    linkedin_teaser?: string | null;
};

/**
 * UpdatePassword
 */
export type UpdatePassword = {
    /**
     * Current Password
     */
    current_password: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * UserActivitiesPublic
 */
export type UserActivitiesPublic = {
    /**
     * Data
     */
    data: Array<UserActivityPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * UserActivityPublic
 */
export type UserActivityPublic = {
    /**
     * Method
     */
    method: string;
    /**
     * Path
     */
    path: string;
    /**
     * Status Code
     */
    status_code: number;
    /**
     * Ip Address
     */
    ip_address?: string | null;
    /**
     * User Agent
     */
    user_agent?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * User Id
     */
    user_id: string | null;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    role?: UserRole;
    /**
     * Password
     */
    password: string;
};

/**
 * UserPublic
 */
export type UserPublic = {
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    role?: UserRole;
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * UserRegister
 */
export type UserRegister = {
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
};

/**
 * UserRole
 */
export type UserRole = 'super' | 'admin' | 'editor' | 'publisher' | 'user';

/**
 * UserUpdate
 */
export type UserUpdate = {
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Email
     */
    email?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
    role?: UserRole | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type MetricsMetricsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/metrics';
};

export type MetricsMetricsGetErrors = {
    /**
     * Bad Request
     */
    400: ErrorDetail;
    /**
     * Forbidden
     */
    403: ErrorDetail;
    /**
     * Not Found
     */
    404: ErrorDetail;
};

export type MetricsMetricsGetError = MetricsMetricsGetErrors[keyof MetricsMetricsGetErrors];

export type MetricsMetricsGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type CheckDatabaseConnectionApiV1CheckDbConnectionGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/checkDBConnection';
};

export type CheckDatabaseConnectionApiV1CheckDbConnectionGetErrors = {
    /**
     * Bad Request
     */
    400: ErrorDetail;
    /**
     * Forbidden
     */
    403: ErrorDetail;
    /**
     * Not Found
     */
    404: ErrorDetail;
};

export type CheckDatabaseConnectionApiV1CheckDbConnectionGetError = CheckDatabaseConnectionApiV1CheckDbConnectionGetErrors[keyof CheckDatabaseConnectionApiV1CheckDbConnectionGetErrors];

export type CheckDatabaseConnectionApiV1CheckDbConnectionGetResponses = {
    /**
     * Response Check Database Connection Api V1 Checkdbconnection Get
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type CheckDatabaseConnectionApiV1CheckDbConnectionGetResponse = CheckDatabaseConnectionApiV1CheckDbConnectionGetResponses[keyof CheckDatabaseConnectionApiV1CheckDbConnectionGetResponses];

export type GetEnvSettingsApiV1GetEnvironmentGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/getEnvironment';
};

export type GetEnvSettingsApiV1GetEnvironmentGetErrors = {
    /**
     * Bad Request
     */
    400: ErrorDetail;
    /**
     * Forbidden
     */
    403: ErrorDetail;
    /**
     * Not Found
     */
    404: ErrorDetail;
};

export type GetEnvSettingsApiV1GetEnvironmentGetError = GetEnvSettingsApiV1GetEnvironmentGetErrors[keyof GetEnvSettingsApiV1GetEnvironmentGetErrors];

export type GetEnvSettingsApiV1GetEnvironmentGetResponses = {
    /**
     * Response Get Env Settings Api V1 Getenvironment Get
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type GetEnvSettingsApiV1GetEnvironmentGetResponse = GetEnvSettingsApiV1GetEnvironmentGetResponses[keyof GetEnvSettingsApiV1GetEnvironmentGetResponses];

export type GetCustomWelcomeMessageApiV1UserNameGetData = {
    body?: never;
    path: {
        /**
         * User Name
         */
        user_name: string;
    };
    query?: never;
    url: '/api/v1/{user_name}';
};

export type GetCustomWelcomeMessageApiV1UserNameGetErrors = {
    /**
     * Bad Request
     */
    400: ErrorDetail;
    /**
     * Forbidden
     */
    403: ErrorDetail;
    /**
     * Not Found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetCustomWelcomeMessageApiV1UserNameGetError = GetCustomWelcomeMessageApiV1UserNameGetErrors[keyof GetCustomWelcomeMessageApiV1UserNameGetErrors];

export type GetCustomWelcomeMessageApiV1UserNameGetResponses = {
    /**
     * Response Get Custom Welcome Message Api V1  User Name  Get
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type GetCustomWelcomeMessageApiV1UserNameGetResponse = GetCustomWelcomeMessageApiV1UserNameGetResponses[keyof GetCustomWelcomeMessageApiV1UserNameGetResponses];

export type GetWelcomeMessageApiV1GetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/';
};

export type GetWelcomeMessageApiV1GetErrors = {
    /**
     * Bad Request
     */
    400: ErrorDetail;
    /**
     * Forbidden
     */
    403: ErrorDetail;
    /**
     * Not Found
     */
    404: ErrorDetail;
};

export type GetWelcomeMessageApiV1GetError = GetWelcomeMessageApiV1GetErrors[keyof GetWelcomeMessageApiV1GetErrors];

export type GetWelcomeMessageApiV1GetResponses = {
    /**
     * Response Get Welcome Message Api V1  Get
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type GetWelcomeMessageApiV1GetResponse = GetWelcomeMessageApiV1GetResponses[keyof GetWelcomeMessageApiV1GetResponses];

export type ReadUsersApiV1UsersGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/';
};

export type ReadUsersApiV1UsersGetErrors = {
    /**
     * Bad Request
     */
    400: ErrorDetail;
    /**
     * Forbidden
     */
    403: ErrorDetail;
    /**
     * Not Found
     */
    404: ErrorDetail;
};

export type ReadUsersApiV1UsersGetError = ReadUsersApiV1UsersGetErrors[keyof ReadUsersApiV1UsersGetErrors];

export type ReadUsersApiV1UsersGetResponses = {
    /**
     * Successful Response
     */
    200: PageUserPublic;
};

export type ReadUsersApiV1UsersGetResponse = ReadUsersApiV1UsersGetResponses[keyof ReadUsersApiV1UsersGetResponses];

export type CreateUserApiV1UsersPostData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/users/';
};

export type CreateUserApiV1UsersPostErrors = {
    /**
     * Bad Request
     */
    400: ErrorDetail;
    /**
     * Forbidden
     */
    403: ErrorDetail;
    /**
     * Not Found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateUserApiV1UsersPostError = CreateUserApiV1UsersPostErrors[keyof CreateUserApiV1UsersPostErrors];

export type CreateUserApiV1UsersPostResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type CreateUserApiV1UsersPostResponse = CreateUserApiV1UsersPostResponses[keyof CreateUserApiV1UsersPostResponses];

export type ReadUserByIdApiV1UsersByIdIdGetData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/users/byID/{id}';
};

export type ReadUserByIdApiV1UsersByIdIdGetErrors = {
    /**
     * Bad Request
     */
    400: ErrorDetail;
    /**
     * Forbidden
     */
    403: ErrorDetail;
    /**
     * Not Found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadUserByIdApiV1UsersByIdIdGetError = ReadUserByIdApiV1UsersByIdIdGetErrors[keyof ReadUserByIdApiV1UsersByIdIdGetErrors];

export type ReadUserByIdApiV1UsersByIdIdGetResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type ReadUserByIdApiV1UsersByIdIdGetResponse = ReadUserByIdApiV1UsersByIdIdGetResponses[keyof ReadUserByIdApiV1UsersByIdIdGetResponses];

export type ReadUserByEmailApiV1UsersByEmailEmailGetData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/v1/users/byEmail/{email}';
};

export type ReadUserByEmailApiV1UsersByEmailEmailGetErrors = {
    /**
     * Bad Request
     */
    400: ErrorDetail;
    /**
     * Forbidden
     */
    403: ErrorDetail;
    /**
     * Not Found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadUserByEmailApiV1UsersByEmailEmailGetError = ReadUserByEmailApiV1UsersByEmailEmailGetErrors[keyof ReadUserByEmailApiV1UsersByEmailEmailGetErrors];

export type ReadUserByEmailApiV1UsersByEmailEmailGetResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type ReadUserByEmailApiV1UsersByEmailEmailGetResponse = ReadUserByEmailApiV1UsersByEmailEmailGetResponses[keyof ReadUserByEmailApiV1UsersByEmailEmailGetResponses];

export type ReadPasswordHistoryApiV1UsersMePasswordHistoryGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me/password-history';
};

export type ReadPasswordHistoryApiV1UsersMePasswordHistoryGetErrors = {
    /**
     * Bad Request
     */
    400: ErrorDetail;
    /**
     * Forbidden
     */
    403: ErrorDetail;
    /**
     * Not Found
     */
    404: ErrorDetail;
};

export type ReadPasswordHistoryApiV1UsersMePasswordHistoryGetError = ReadPasswordHistoryApiV1UsersMePasswordHistoryGetErrors[keyof ReadPasswordHistoryApiV1UsersMePasswordHistoryGetErrors];

export type ReadPasswordHistoryApiV1UsersMePasswordHistoryGetResponses = {
    /**
     * Successful Response
     */
    200: PasswordHistoriesPublic;
};

export type ReadPasswordHistoryApiV1UsersMePasswordHistoryGetResponse = ReadPasswordHistoryApiV1UsersMePasswordHistoryGetResponses[keyof ReadPasswordHistoryApiV1UsersMePasswordHistoryGetResponses];

export type UpdatePasswordApiV1UsersPasswordPatchData = {
    body: UpdatePassword;
    path?: never;
    query?: never;
    url: '/api/v1/users/password';
};

export type UpdatePasswordApiV1UsersPasswordPatchErrors = {
    /**
     * Bad Request
     */
    400: ErrorDetail;
    /**
     * Forbidden
     */
    403: ErrorDetail;
    /**
     * Not Found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdatePasswordApiV1UsersPasswordPatchError = UpdatePasswordApiV1UsersPasswordPatchErrors[keyof UpdatePasswordApiV1UsersPasswordPatchErrors];

export type UpdatePasswordApiV1UsersPasswordPatchResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type UpdatePasswordApiV1UsersPasswordPatchResponse = UpdatePasswordApiV1UsersPasswordPatchResponses[keyof UpdatePasswordApiV1UsersPasswordPatchResponses];

export type DeleteUserApiV1UsersIdDeleteData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/users/{id}';
};

export type DeleteUserApiV1UsersIdDeleteErrors = {
    /**
     * Bad Request
     */
    400: ErrorDetail;
    /**
     * Forbidden
     */
    403: ErrorDetail;
    /**
     * Not Found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteUserApiV1UsersIdDeleteError = DeleteUserApiV1UsersIdDeleteErrors[keyof DeleteUserApiV1UsersIdDeleteErrors];

export type DeleteUserApiV1UsersIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type DeleteUserApiV1UsersIdDeleteResponse = DeleteUserApiV1UsersIdDeleteResponses[keyof DeleteUserApiV1UsersIdDeleteResponses];

export type UpdateUserApiV1UsersIdPatchData = {
    body: UserUpdate;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/users/{id}';
};

export type UpdateUserApiV1UsersIdPatchErrors = {
    /**
     * Bad Request
     */
    400: ErrorDetail;
    /**
     * Forbidden
     */
    403: ErrorDetail;
    /**
     * Not Found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateUserApiV1UsersIdPatchError = UpdateUserApiV1UsersIdPatchErrors[keyof UpdateUserApiV1UsersIdPatchErrors];

export type UpdateUserApiV1UsersIdPatchResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UpdateUserApiV1UsersIdPatchResponse = UpdateUserApiV1UsersIdPatchResponses[keyof UpdateUserApiV1UsersIdPatchResponses];

export type LoginAccessTokenApiV1LoginAccessTokenPostData = {
    body: BodyLoginAccessTokenApiV1LoginAccessTokenPost;
    path?: never;
    query?: never;
    url: '/api/v1/login/access-token';
};

export type LoginAccessTokenApiV1LoginAccessTokenPostErrors = {
    /**
     * Bad Request
     */
    400: ErrorDetail;
    /**
     * Forbidden
     */
    403: ErrorDetail;
    /**
     * Not Found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginAccessTokenApiV1LoginAccessTokenPostError = LoginAccessTokenApiV1LoginAccessTokenPostErrors[keyof LoginAccessTokenApiV1LoginAccessTokenPostErrors];

export type LoginAccessTokenApiV1LoginAccessTokenPostResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type LoginAccessTokenApiV1LoginAccessTokenPostResponse = LoginAccessTokenApiV1LoginAccessTokenPostResponses[keyof LoginAccessTokenApiV1LoginAccessTokenPostResponses];

export type ReadSecureApiV1LoginSecureDataGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/login/secure-data';
};

export type ReadSecureApiV1LoginSecureDataGetErrors = {
    /**
     * Bad Request
     */
    400: ErrorDetail;
    /**
     * Forbidden
     */
    403: ErrorDetail;
    /**
     * Not Found
     */
    404: ErrorDetail;
};

export type ReadSecureApiV1LoginSecureDataGetError = ReadSecureApiV1LoginSecureDataGetErrors[keyof ReadSecureApiV1LoginSecureDataGetErrors];

export type ReadSecureApiV1LoginSecureDataGetResponses = {
    /**
     * Response Read Secure Api V1 Login Secure Data Get
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type ReadSecureApiV1LoginSecureDataGetResponse = ReadSecureApiV1LoginSecureDataGetResponses[keyof ReadSecureApiV1LoginSecureDataGetResponses];

export type GetCurrentUserApiV1LoginCurrentUserGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/login/current-user';
};

export type GetCurrentUserApiV1LoginCurrentUserGetErrors = {
    /**
     * Bad Request
     */
    400: ErrorDetail;
    /**
     * Forbidden
     */
    403: ErrorDetail;
    /**
     * Not Found
     */
    404: ErrorDetail;
};

export type GetCurrentUserApiV1LoginCurrentUserGetError = GetCurrentUserApiV1LoginCurrentUserGetErrors[keyof GetCurrentUserApiV1LoginCurrentUserGetErrors];

export type GetCurrentUserApiV1LoginCurrentUserGetResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type GetCurrentUserApiV1LoginCurrentUserGetResponse = GetCurrentUserApiV1LoginCurrentUserGetResponses[keyof GetCurrentUserApiV1LoginCurrentUserGetResponses];

export type RegisterUserApiV1LoginSignupPostData = {
    body: UserRegister;
    path?: never;
    query?: never;
    url: '/api/v1/login/signup';
};

export type RegisterUserApiV1LoginSignupPostErrors = {
    /**
     * Bad Request
     */
    400: ErrorDetail;
    /**
     * Forbidden
     */
    403: ErrorDetail;
    /**
     * Not Found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RegisterUserApiV1LoginSignupPostError = RegisterUserApiV1LoginSignupPostErrors[keyof RegisterUserApiV1LoginSignupPostErrors];

export type RegisterUserApiV1LoginSignupPostResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type RegisterUserApiV1LoginSignupPostResponse = RegisterUserApiV1LoginSignupPostResponses[keyof RegisterUserApiV1LoginSignupPostResponses];

export type RecoverPasswordApiV1LoginPasswordRecoveryEmailPostData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/v1/login/password-recovery/{email}';
};

export type RecoverPasswordApiV1LoginPasswordRecoveryEmailPostErrors = {
    /**
     * Bad Request
     */
    400: ErrorDetail;
    /**
     * Forbidden
     */
    403: ErrorDetail;
    /**
     * Not Found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RecoverPasswordApiV1LoginPasswordRecoveryEmailPostError = RecoverPasswordApiV1LoginPasswordRecoveryEmailPostErrors[keyof RecoverPasswordApiV1LoginPasswordRecoveryEmailPostErrors];

export type RecoverPasswordApiV1LoginPasswordRecoveryEmailPostResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type RecoverPasswordApiV1LoginPasswordRecoveryEmailPostResponse = RecoverPasswordApiV1LoginPasswordRecoveryEmailPostResponses[keyof RecoverPasswordApiV1LoginPasswordRecoveryEmailPostResponses];

export type ReadMyActivitiesApiV1ActivitiesMeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/activities/me';
};

export type ReadMyActivitiesApiV1ActivitiesMeGetErrors = {
    /**
     * Bad Request
     */
    400: ErrorDetail;
    /**
     * Forbidden
     */
    403: ErrorDetail;
    /**
     * Not Found
     */
    404: ErrorDetail;
};

export type ReadMyActivitiesApiV1ActivitiesMeGetError = ReadMyActivitiesApiV1ActivitiesMeGetErrors[keyof ReadMyActivitiesApiV1ActivitiesMeGetErrors];

export type ReadMyActivitiesApiV1ActivitiesMeGetResponses = {
    /**
     * Successful Response
     */
    200: UserActivitiesPublic;
};

export type ReadMyActivitiesApiV1ActivitiesMeGetResponse = ReadMyActivitiesApiV1ActivitiesMeGetResponses[keyof ReadMyActivitiesApiV1ActivitiesMeGetResponses];

export type ReadAllActivitiesApiV1ActivitiesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/activities/';
};

export type ReadAllActivitiesApiV1ActivitiesGetErrors = {
    /**
     * Bad Request
     */
    400: ErrorDetail;
    /**
     * Forbidden
     */
    403: ErrorDetail;
    /**
     * Not Found
     */
    404: ErrorDetail;
};

export type ReadAllActivitiesApiV1ActivitiesGetError = ReadAllActivitiesApiV1ActivitiesGetErrors[keyof ReadAllActivitiesApiV1ActivitiesGetErrors];

export type ReadAllActivitiesApiV1ActivitiesGetResponses = {
    /**
     * Successful Response
     */
    200: PageUserActivityPublic;
};

export type ReadAllActivitiesApiV1ActivitiesGetResponse = ReadAllActivitiesApiV1ActivitiesGetResponses[keyof ReadAllActivitiesApiV1ActivitiesGetResponses];

export type ReadPlatformConfigApiV1SettingsPlatformGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/settings/platform';
};

export type ReadPlatformConfigApiV1SettingsPlatformGetErrors = {
    /**
     * Bad Request
     */
    400: ErrorDetail;
    /**
     * Forbidden
     */
    403: ErrorDetail;
    /**
     * Not Found
     */
    404: ErrorDetail;
};

export type ReadPlatformConfigApiV1SettingsPlatformGetError = ReadPlatformConfigApiV1SettingsPlatformGetErrors[keyof ReadPlatformConfigApiV1SettingsPlatformGetErrors];

export type ReadPlatformConfigApiV1SettingsPlatformGetResponses = {
    /**
     * Successful Response
     */
    200: PlatformConfigPublic;
};

export type ReadPlatformConfigApiV1SettingsPlatformGetResponse = ReadPlatformConfigApiV1SettingsPlatformGetResponses[keyof ReadPlatformConfigApiV1SettingsPlatformGetResponses];

export type UpdatePlatformConfigApiV1SettingsPlatformPatchData = {
    body: PlatformConfigUpdate;
    path?: never;
    query?: never;
    url: '/api/v1/settings/platform';
};

export type UpdatePlatformConfigApiV1SettingsPlatformPatchErrors = {
    /**
     * Bad Request
     */
    400: ErrorDetail;
    /**
     * Forbidden
     */
    403: ErrorDetail;
    /**
     * Not Found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdatePlatformConfigApiV1SettingsPlatformPatchError = UpdatePlatformConfigApiV1SettingsPlatformPatchErrors[keyof UpdatePlatformConfigApiV1SettingsPlatformPatchErrors];

export type UpdatePlatformConfigApiV1SettingsPlatformPatchResponses = {
    /**
     * Successful Response
     */
    200: PlatformConfigPublic;
};

export type UpdatePlatformConfigApiV1SettingsPlatformPatchResponse = UpdatePlatformConfigApiV1SettingsPlatformPatchResponses[keyof UpdatePlatformConfigApiV1SettingsPlatformPatchResponses];

export type ReadAiModelsCatalogApiV1SettingsAiModelsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Ollama Base Url
         */
        ollama_base_url?: string | null;
    };
    url: '/api/v1/settings/ai/models';
};

export type ReadAiModelsCatalogApiV1SettingsAiModelsGetErrors = {
    /**
     * Bad Request
     */
    400: ErrorDetail;
    /**
     * Forbidden
     */
    403: ErrorDetail;
    /**
     * Not Found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadAiModelsCatalogApiV1SettingsAiModelsGetError = ReadAiModelsCatalogApiV1SettingsAiModelsGetErrors[keyof ReadAiModelsCatalogApiV1SettingsAiModelsGetErrors];

export type ReadAiModelsCatalogApiV1SettingsAiModelsGetResponses = {
    /**
     * Successful Response
     */
    200: AiModelsCatalogPublic;
};

export type ReadAiModelsCatalogApiV1SettingsAiModelsGetResponse = ReadAiModelsCatalogApiV1SettingsAiModelsGetResponses[keyof ReadAiModelsCatalogApiV1SettingsAiModelsGetResponses];

export type ReadAiConfigApiV1SettingsAiGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/settings/ai';
};

export type ReadAiConfigApiV1SettingsAiGetErrors = {
    /**
     * Bad Request
     */
    400: ErrorDetail;
    /**
     * Forbidden
     */
    403: ErrorDetail;
    /**
     * Not Found
     */
    404: ErrorDetail;
};

export type ReadAiConfigApiV1SettingsAiGetError = ReadAiConfigApiV1SettingsAiGetErrors[keyof ReadAiConfigApiV1SettingsAiGetErrors];

export type ReadAiConfigApiV1SettingsAiGetResponses = {
    /**
     * Successful Response
     */
    200: AiAgentConfigPublic;
};

export type ReadAiConfigApiV1SettingsAiGetResponse = ReadAiConfigApiV1SettingsAiGetResponses[keyof ReadAiConfigApiV1SettingsAiGetResponses];

export type UpdateAiConfigApiV1SettingsAiPatchData = {
    body: AiAgentConfigUpdate;
    path?: never;
    query?: never;
    url: '/api/v1/settings/ai';
};

export type UpdateAiConfigApiV1SettingsAiPatchErrors = {
    /**
     * Bad Request
     */
    400: ErrorDetail;
    /**
     * Forbidden
     */
    403: ErrorDetail;
    /**
     * Not Found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateAiConfigApiV1SettingsAiPatchError = UpdateAiConfigApiV1SettingsAiPatchErrors[keyof UpdateAiConfigApiV1SettingsAiPatchErrors];

export type UpdateAiConfigApiV1SettingsAiPatchResponses = {
    /**
     * Successful Response
     */
    200: AiAgentConfigPublic;
};

export type UpdateAiConfigApiV1SettingsAiPatchResponse = UpdateAiConfigApiV1SettingsAiPatchResponses[keyof UpdateAiConfigApiV1SettingsAiPatchResponses];

export type CreateCustomAiProviderApiV1SettingsAiProvidersPostData = {
    body: CustomAiProviderCreate;
    path?: never;
    query?: never;
    url: '/api/v1/settings/ai/providers';
};

export type CreateCustomAiProviderApiV1SettingsAiProvidersPostErrors = {
    /**
     * Bad Request
     */
    400: ErrorDetail;
    /**
     * Forbidden
     */
    403: ErrorDetail;
    /**
     * Not Found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateCustomAiProviderApiV1SettingsAiProvidersPostError = CreateCustomAiProviderApiV1SettingsAiProvidersPostErrors[keyof CreateCustomAiProviderApiV1SettingsAiProvidersPostErrors];

export type CreateCustomAiProviderApiV1SettingsAiProvidersPostResponses = {
    /**
     * Successful Response
     */
    200: CustomAiProviderPublic;
};

export type CreateCustomAiProviderApiV1SettingsAiProvidersPostResponse = CreateCustomAiProviderApiV1SettingsAiProvidersPostResponses[keyof CreateCustomAiProviderApiV1SettingsAiProvidersPostResponses];

export type DeleteCustomAiProviderApiV1SettingsAiProvidersProviderIdDeleteData = {
    body?: never;
    path: {
        /**
         * Provider Id
         */
        provider_id: string;
    };
    query?: never;
    url: '/api/v1/settings/ai/providers/{provider_id}';
};

export type DeleteCustomAiProviderApiV1SettingsAiProvidersProviderIdDeleteErrors = {
    /**
     * Bad Request
     */
    400: ErrorDetail;
    /**
     * Forbidden
     */
    403: ErrorDetail;
    /**
     * Not Found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteCustomAiProviderApiV1SettingsAiProvidersProviderIdDeleteError = DeleteCustomAiProviderApiV1SettingsAiProvidersProviderIdDeleteErrors[keyof DeleteCustomAiProviderApiV1SettingsAiProvidersProviderIdDeleteErrors];

export type DeleteCustomAiProviderApiV1SettingsAiProvidersProviderIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteCustomAiProviderApiV1SettingsAiProvidersProviderIdDeleteResponse = DeleteCustomAiProviderApiV1SettingsAiProvidersProviderIdDeleteResponses[keyof DeleteCustomAiProviderApiV1SettingsAiProvidersProviderIdDeleteResponses];

export type RefreshProviderModelsApiV1SettingsAiProvidersProviderSlugRefreshModelsPostData = {
    body?: never;
    path: {
        /**
         * Provider Slug
         */
        provider_slug: string;
    };
    query?: {
        /**
         * Ollama Base Url
         */
        ollama_base_url?: string | null;
    };
    url: '/api/v1/settings/ai/providers/{provider_slug}/refresh-models';
};

export type RefreshProviderModelsApiV1SettingsAiProvidersProviderSlugRefreshModelsPostErrors = {
    /**
     * Bad Request
     */
    400: ErrorDetail;
    /**
     * Forbidden
     */
    403: ErrorDetail;
    /**
     * Not Found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RefreshProviderModelsApiV1SettingsAiProvidersProviderSlugRefreshModelsPostError = RefreshProviderModelsApiV1SettingsAiProvidersProviderSlugRefreshModelsPostErrors[keyof RefreshProviderModelsApiV1SettingsAiProvidersProviderSlugRefreshModelsPostErrors];

export type RefreshProviderModelsApiV1SettingsAiProvidersProviderSlugRefreshModelsPostResponses = {
    /**
     * Successful Response
     */
    200: ProviderModelsRefreshPublic;
};

export type RefreshProviderModelsApiV1SettingsAiProvidersProviderSlugRefreshModelsPostResponse = RefreshProviderModelsApiV1SettingsAiProvidersProviderSlugRefreshModelsPostResponses[keyof RefreshProviderModelsApiV1SettingsAiProvidersProviderSlugRefreshModelsPostResponses];

export type ListContentDraftsApiV1ContentDraftsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/content/drafts/';
};

export type ListContentDraftsApiV1ContentDraftsGetErrors = {
    /**
     * Bad Request
     */
    400: ErrorDetail;
    /**
     * Forbidden
     */
    403: ErrorDetail;
    /**
     * Not Found
     */
    404: ErrorDetail;
};

export type ListContentDraftsApiV1ContentDraftsGetError = ListContentDraftsApiV1ContentDraftsGetErrors[keyof ListContentDraftsApiV1ContentDraftsGetErrors];

export type ListContentDraftsApiV1ContentDraftsGetResponses = {
    /**
     * Successful Response
     */
    200: ContentDraftsPublic;
};

export type ListContentDraftsApiV1ContentDraftsGetResponse = ListContentDraftsApiV1ContentDraftsGetResponses[keyof ListContentDraftsApiV1ContentDraftsGetResponses];

export type DeleteContentDraftApiV1ContentDraftsDraftIdDeleteData = {
    body?: never;
    path: {
        /**
         * Draft Id
         */
        draft_id: string;
    };
    query?: never;
    url: '/api/v1/content/drafts/{draft_id}';
};

export type DeleteContentDraftApiV1ContentDraftsDraftIdDeleteErrors = {
    /**
     * Bad Request
     */
    400: ErrorDetail;
    /**
     * Forbidden
     */
    403: ErrorDetail;
    /**
     * Not Found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteContentDraftApiV1ContentDraftsDraftIdDeleteError = DeleteContentDraftApiV1ContentDraftsDraftIdDeleteErrors[keyof DeleteContentDraftApiV1ContentDraftsDraftIdDeleteErrors];

export type DeleteContentDraftApiV1ContentDraftsDraftIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteContentDraftApiV1ContentDraftsDraftIdDeleteResponse = DeleteContentDraftApiV1ContentDraftsDraftIdDeleteResponses[keyof DeleteContentDraftApiV1ContentDraftsDraftIdDeleteResponses];

export type GetContentDraftApiV1ContentDraftsDraftIdGetData = {
    body?: never;
    path: {
        /**
         * Draft Id
         */
        draft_id: string;
    };
    query?: never;
    url: '/api/v1/content/drafts/{draft_id}';
};

export type GetContentDraftApiV1ContentDraftsDraftIdGetErrors = {
    /**
     * Bad Request
     */
    400: ErrorDetail;
    /**
     * Forbidden
     */
    403: ErrorDetail;
    /**
     * Not Found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetContentDraftApiV1ContentDraftsDraftIdGetError = GetContentDraftApiV1ContentDraftsDraftIdGetErrors[keyof GetContentDraftApiV1ContentDraftsDraftIdGetErrors];

export type GetContentDraftApiV1ContentDraftsDraftIdGetResponses = {
    /**
     * Successful Response
     */
    200: ContentDraftDetailPublic;
};

export type GetContentDraftApiV1ContentDraftsDraftIdGetResponse = GetContentDraftApiV1ContentDraftsDraftIdGetResponses[keyof GetContentDraftApiV1ContentDraftsDraftIdGetResponses];

export type UpdateContentDraftApiV1ContentDraftsDraftIdPatchData = {
    body: UpdateDraftRequest;
    path: {
        /**
         * Draft Id
         */
        draft_id: string;
    };
    query?: never;
    url: '/api/v1/content/drafts/{draft_id}';
};

export type UpdateContentDraftApiV1ContentDraftsDraftIdPatchErrors = {
    /**
     * Bad Request
     */
    400: ErrorDetail;
    /**
     * Forbidden
     */
    403: ErrorDetail;
    /**
     * Not Found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateContentDraftApiV1ContentDraftsDraftIdPatchError = UpdateContentDraftApiV1ContentDraftsDraftIdPatchErrors[keyof UpdateContentDraftApiV1ContentDraftsDraftIdPatchErrors];

export type UpdateContentDraftApiV1ContentDraftsDraftIdPatchResponses = {
    /**
     * Successful Response
     */
    200: ContentDraftDetailPublic;
};

export type UpdateContentDraftApiV1ContentDraftsDraftIdPatchResponse = UpdateContentDraftApiV1ContentDraftsDraftIdPatchResponses[keyof UpdateContentDraftApiV1ContentDraftsDraftIdPatchResponses];

export type GenerateContentDraftApiV1ContentDraftsGeneratePostData = {
    body: GenerateDraftRequest;
    path?: never;
    query?: never;
    url: '/api/v1/content/drafts/generate';
};

export type GenerateContentDraftApiV1ContentDraftsGeneratePostErrors = {
    /**
     * Bad Request
     */
    400: ErrorDetail;
    /**
     * Forbidden
     */
    403: ErrorDetail;
    /**
     * Not Found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GenerateContentDraftApiV1ContentDraftsGeneratePostError = GenerateContentDraftApiV1ContentDraftsGeneratePostErrors[keyof GenerateContentDraftApiV1ContentDraftsGeneratePostErrors];

export type GenerateContentDraftApiV1ContentDraftsGeneratePostResponses = {
    /**
     * Successful Response
     */
    201: ContentDraftDetailPublic;
};

export type GenerateContentDraftApiV1ContentDraftsGeneratePostResponse = GenerateContentDraftApiV1ContentDraftsGeneratePostResponses[keyof GenerateContentDraftApiV1ContentDraftsGeneratePostResponses];

export type UploadContentDraftCoverImageApiV1ContentDraftsDraftIdCoversCoverIdImagePostData = {
    body: BodyUploadContentDraftCoverImageApiV1ContentDraftsDraftIdCoversCoverIdImagePost;
    path: {
        /**
         * Draft Id
         */
        draft_id: string;
        /**
         * Cover Id
         */
        cover_id: string;
    };
    query?: never;
    url: '/api/v1/content/drafts/{draft_id}/covers/{cover_id}/image';
};

export type UploadContentDraftCoverImageApiV1ContentDraftsDraftIdCoversCoverIdImagePostErrors = {
    /**
     * Bad Request
     */
    400: ErrorDetail;
    /**
     * Forbidden
     */
    403: ErrorDetail;
    /**
     * Not Found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadContentDraftCoverImageApiV1ContentDraftsDraftIdCoversCoverIdImagePostError = UploadContentDraftCoverImageApiV1ContentDraftsDraftIdCoversCoverIdImagePostErrors[keyof UploadContentDraftCoverImageApiV1ContentDraftsDraftIdCoversCoverIdImagePostErrors];

export type UploadContentDraftCoverImageApiV1ContentDraftsDraftIdCoversCoverIdImagePostResponses = {
    /**
     * Successful Response
     */
    200: ContentDraftDetailPublic;
};

export type UploadContentDraftCoverImageApiV1ContentDraftsDraftIdCoversCoverIdImagePostResponse = UploadContentDraftCoverImageApiV1ContentDraftsDraftIdCoversCoverIdImagePostResponses[keyof UploadContentDraftCoverImageApiV1ContentDraftsDraftIdCoversCoverIdImagePostResponses];

export type ApproveContentDraftApiV1ContentDraftsDraftIdApprovePostData = {
    body?: never;
    path: {
        /**
         * Draft Id
         */
        draft_id: string;
    };
    query?: never;
    url: '/api/v1/content/drafts/{draft_id}/approve';
};

export type ApproveContentDraftApiV1ContentDraftsDraftIdApprovePostErrors = {
    /**
     * Bad Request
     */
    400: ErrorDetail;
    /**
     * Forbidden
     */
    403: ErrorDetail;
    /**
     * Not Found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ApproveContentDraftApiV1ContentDraftsDraftIdApprovePostError = ApproveContentDraftApiV1ContentDraftsDraftIdApprovePostErrors[keyof ApproveContentDraftApiV1ContentDraftsDraftIdApprovePostErrors];

export type ApproveContentDraftApiV1ContentDraftsDraftIdApprovePostResponses = {
    /**
     * Successful Response
     */
    200: ContentDraftDetailPublic;
};

export type ApproveContentDraftApiV1ContentDraftsDraftIdApprovePostResponse = ApproveContentDraftApiV1ContentDraftsDraftIdApprovePostResponses[keyof ApproveContentDraftApiV1ContentDraftsDraftIdApprovePostResponses];

export type RescheduleContentDraftApiV1ContentDraftsDraftIdSchedulePatchData = {
    body: RescheduleDraftRequest;
    path: {
        /**
         * Draft Id
         */
        draft_id: string;
    };
    query?: never;
    url: '/api/v1/content/drafts/{draft_id}/schedule';
};

export type RescheduleContentDraftApiV1ContentDraftsDraftIdSchedulePatchErrors = {
    /**
     * Bad Request
     */
    400: ErrorDetail;
    /**
     * Forbidden
     */
    403: ErrorDetail;
    /**
     * Not Found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RescheduleContentDraftApiV1ContentDraftsDraftIdSchedulePatchError = RescheduleContentDraftApiV1ContentDraftsDraftIdSchedulePatchErrors[keyof RescheduleContentDraftApiV1ContentDraftsDraftIdSchedulePatchErrors];

export type RescheduleContentDraftApiV1ContentDraftsDraftIdSchedulePatchResponses = {
    /**
     * Successful Response
     */
    200: PublishStatusPublic;
};

export type RescheduleContentDraftApiV1ContentDraftsDraftIdSchedulePatchResponse = RescheduleContentDraftApiV1ContentDraftsDraftIdSchedulePatchResponses[keyof RescheduleContentDraftApiV1ContentDraftsDraftIdSchedulePatchResponses];

export type ScheduleContentDraftApiV1ContentDraftsDraftIdSchedulePostData = {
    /**
     * Body
     */
    body?: ScheduleDraftRequest | null;
    path: {
        /**
         * Draft Id
         */
        draft_id: string;
    };
    query?: never;
    url: '/api/v1/content/drafts/{draft_id}/schedule';
};

export type ScheduleContentDraftApiV1ContentDraftsDraftIdSchedulePostErrors = {
    /**
     * Bad Request
     */
    400: ErrorDetail;
    /**
     * Forbidden
     */
    403: ErrorDetail;
    /**
     * Not Found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ScheduleContentDraftApiV1ContentDraftsDraftIdSchedulePostError = ScheduleContentDraftApiV1ContentDraftsDraftIdSchedulePostErrors[keyof ScheduleContentDraftApiV1ContentDraftsDraftIdSchedulePostErrors];

export type ScheduleContentDraftApiV1ContentDraftsDraftIdSchedulePostResponses = {
    /**
     * Successful Response
     */
    200: PublishStatusPublic;
};

export type ScheduleContentDraftApiV1ContentDraftsDraftIdSchedulePostResponse = ScheduleContentDraftApiV1ContentDraftsDraftIdSchedulePostResponses[keyof ScheduleContentDraftApiV1ContentDraftsDraftIdSchedulePostResponses];

export type GetContentDraftPublishStatusApiV1ContentDraftsDraftIdPublishStatusGetData = {
    body?: never;
    path: {
        /**
         * Draft Id
         */
        draft_id: string;
    };
    query?: never;
    url: '/api/v1/content/drafts/{draft_id}/publish-status';
};

export type GetContentDraftPublishStatusApiV1ContentDraftsDraftIdPublishStatusGetErrors = {
    /**
     * Bad Request
     */
    400: ErrorDetail;
    /**
     * Forbidden
     */
    403: ErrorDetail;
    /**
     * Not Found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetContentDraftPublishStatusApiV1ContentDraftsDraftIdPublishStatusGetError = GetContentDraftPublishStatusApiV1ContentDraftsDraftIdPublishStatusGetErrors[keyof GetContentDraftPublishStatusApiV1ContentDraftsDraftIdPublishStatusGetErrors];

export type GetContentDraftPublishStatusApiV1ContentDraftsDraftIdPublishStatusGetResponses = {
    /**
     * Successful Response
     */
    200: PublishStatusPublic;
};

export type GetContentDraftPublishStatusApiV1ContentDraftsDraftIdPublishStatusGetResponse = GetContentDraftPublishStatusApiV1ContentDraftsDraftIdPublishStatusGetResponses[keyof GetContentDraftPublishStatusApiV1ContentDraftsDraftIdPublishStatusGetResponses];

export type RetryContentDraftPublishApiV1ContentDraftsDraftIdRetryPublishPostData = {
    body?: never;
    path: {
        /**
         * Draft Id
         */
        draft_id: string;
    };
    query?: never;
    url: '/api/v1/content/drafts/{draft_id}/retry-publish';
};

export type RetryContentDraftPublishApiV1ContentDraftsDraftIdRetryPublishPostErrors = {
    /**
     * Bad Request
     */
    400: ErrorDetail;
    /**
     * Forbidden
     */
    403: ErrorDetail;
    /**
     * Not Found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RetryContentDraftPublishApiV1ContentDraftsDraftIdRetryPublishPostError = RetryContentDraftPublishApiV1ContentDraftsDraftIdRetryPublishPostErrors[keyof RetryContentDraftPublishApiV1ContentDraftsDraftIdRetryPublishPostErrors];

export type RetryContentDraftPublishApiV1ContentDraftsDraftIdRetryPublishPostResponses = {
    /**
     * Successful Response
     */
    200: PublishStatusPublic;
};

export type RetryContentDraftPublishApiV1ContentDraftsDraftIdRetryPublishPostResponse = RetryContentDraftPublishApiV1ContentDraftsDraftIdRetryPublishPostResponses[keyof RetryContentDraftPublishApiV1ContentDraftsDraftIdRetryPublishPostResponses];

export type HealthHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthHealthGetErrors = {
    /**
     * Bad Request
     */
    400: ErrorDetail;
    /**
     * Forbidden
     */
    403: ErrorDetail;
    /**
     * Not Found
     */
    404: ErrorDetail;
};

export type HealthHealthGetError = HealthHealthGetErrors[keyof HealthHealthGetErrors];

export type HealthHealthGetResponses = {
    /**
     * Response Health Health Get
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type HealthHealthGetResponse = HealthHealthGetResponses[keyof HealthHealthGetResponses];

export type TestEmailTestEmailPostData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Email To
         */
        email_to: string;
    };
    url: '/test-email/';
};

export type TestEmailTestEmailPostErrors = {
    /**
     * Bad Request
     */
    400: ErrorDetail;
    /**
     * Forbidden
     */
    403: ErrorDetail;
    /**
     * Not Found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TestEmailTestEmailPostError = TestEmailTestEmailPostErrors[keyof TestEmailTestEmailPostErrors];

export type TestEmailTestEmailPostResponses = {
    /**
     * Successful Response
     */
    201: Message;
};

export type TestEmailTestEmailPostResponse = TestEmailTestEmailPostResponses[keyof TestEmailTestEmailPostResponses];
