"""sprint1_content_and_settings

Revision ID: 030cb1d54852
Revises: a1d2e3f4b5c6
Create Date: 2026-06-15 20:09:46.912809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '030cb1d54852'
down_revision: Union[str, Sequence[str], None] = 'a1d2e3f4b5c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_agent_config',
    sa.Column('provider', sa.Enum('OPENAI', 'ANTHROPIC', name='aiprovider'), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('system_prompt', sqlmodel.sql.sqltypes.AutoString(length=8000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('openai_api_key_encrypted', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True),
    sa.Column('anthropic_api_key_encrypted', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_agent_config_user_id'), 'ai_agent_config', ['user_id'], unique=True)
    op.create_table('content_draft',
    sa.Column('topic', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('user_prompt', sqlmodel.sql.sqltypes.AutoString(length=4000), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'APPROVED', 'SCHEDULED', 'PUBLISHED', 'PARTIALLY_PUBLISHED', 'FAILED', name='contentdraftstatus'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_draft_user_id'), 'content_draft', ['user_id'], unique=False)
    op.create_table('platform_config',
    sa.Column('devto_enabled', sa.Boolean(), nullable=False),
    sa.Column('linkedin_enabled', sa.Boolean(), nullable=False),
    sa.Column('devto_profile_url', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True),
    sa.Column('linkedin_profile_url', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('devto_api_key_encrypted', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_config_user_id'), 'platform_config', ['user_id'], unique=True)
    op.create_table('cover_image',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('content_draft_id', sa.Uuid(), nullable=False),
    sa.Column('platform', sa.Enum('DEVTO', 'LINKEDIN', name='coverimageplatform'), nullable=False),
    sa.Column('storage_key', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('prompt_used', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['content_draft_id'], ['content_draft.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cover_image_content_draft_id'), 'cover_image', ['content_draft_id'], unique=False)
    op.create_table('publish_job',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('content_draft_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'PARTIAL', name='publishjobstatus'), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('devto_url', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['content_draft_id'], ['content_draft.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publish_job_content_draft_id'), 'publish_job', ['content_draft_id'], unique=False)
    op.create_table('devto_article',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('content_draft_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('body_markdown', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tags', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('cover_image_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['content_draft_id'], ['content_draft.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cover_image_id'], ['cover_image.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_draft_id')
    )
    op.create_index(op.f('ix_devto_article_content_draft_id'), 'devto_article', ['content_draft_id'], unique=False)
    op.create_table('linkedin_post',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('content_draft_id', sa.Uuid(), nullable=False),
    sa.Column('teaser_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('article_url', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True),
    sa.Column('cover_image_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['content_draft_id'], ['content_draft.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cover_image_id'], ['cover_image.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_draft_id')
    )
    op.create_index(op.f('ix_linkedin_post_content_draft_id'), 'linkedin_post', ['content_draft_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_linkedin_post_content_draft_id'), table_name='linkedin_post')
    op.drop_table('linkedin_post')
    op.drop_index(op.f('ix_devto_article_content_draft_id'), table_name='devto_article')
    op.drop_table('devto_article')
    op.drop_index(op.f('ix_publish_job_content_draft_id'), table_name='publish_job')
    op.drop_table('publish_job')
    op.drop_index(op.f('ix_cover_image_content_draft_id'), table_name='cover_image')
    op.drop_table('cover_image')
    op.drop_index(op.f('ix_platform_config_user_id'), table_name='platform_config')
    op.drop_table('platform_config')
    op.drop_index(op.f('ix_content_draft_user_id'), table_name='content_draft')
    op.drop_table('content_draft')
    op.drop_index(op.f('ix_ai_agent_config_user_id'), table_name='ai_agent_config')
    op.drop_table('ai_agent_config')
    # ### end Alembic commands ###
